#!/bin/bash
set -euo pipefail

rm -rf build
mkdir build

cd src-2.0
zip -r ../build/zotrayo-2.0.xpi *
cd ../build

jq ".addons[\"zotrayo@example.com\"].updates[0].update_hash = \"sha256:`shasum -a 256 zotrayo-2.0.xpi | cut -d' ' -f1`\"" ../updates-2.0.json.tmpl > updates-2.0.json
