#!/bin/bash
set -euo pipefail

rm -rf build
mkdir build

cd src
zip -r ../build/zotrayo.xpi *
cd ../build

jq ".addons[\"zotrayo@jaehho.com\"].updates[0].update_hash = \"sha256:`shasum -a 256 zotrayo.xpi | cut -d' ' -f1`\"" ../updates.json.tmpl > updates.json
